
const data = [
    `const path = require('node:path');`,
    `const {env} = require('node:process');`,
    ``,
    ``,
    `env.BASEPATH_BOOTSTRAP4_BUNDLE = '{{env.BASEPATH_BOOTSTRAP4_BUNDLE}}'`,
    `env.NODE_MODULES_BOOTSTRAP4 = '{{env.NODE_MODULES_BOOTSTRAP4}}'`,
    ``,
    ``,
    `const { Bootstrap4 } = require('{{init_cwd}}')`,
    ``,
    ``,
    `const { Bootstrap4Grunt } = require('{{init_cwd}}/src/grunt/bootstrap4-grunt.js');`,
    ``,
    `/** @param {import("grunt")} grunt */`,
    `module.exports = function (grunt) {`,
    `    grunt.loadNpmTasks('grunt-contrib-uglify');`,
    `    grunt.loadNpmTasks('grunt-contrib-sass');`,
    `    grunt.loadNpmTasks('grunt-contrib-concat');`,
    `    grunt.loadNpmTasks('grunt-contrib-copy');`,
    `    grunt.loadNpmTasks('grunt-contrib-watch');`,
    `    grunt.loadNpmTasks('grunt-concat-css');`,
    `    grunt.loadNpmTasks('grunt-shell');`,
    `    grunt.loadNpmTasks('grunt-run');`,
    `    grunt.loadNpmTasks('grunt-banner');`,
    `    grunt.loadNpmTasks('grunt-contrib-cssmin');`,
    `    grunt.loadNpmTasks('grunt-strip-css-comments');`,
    `    `,
    `    Bootstrap4Grunt(grunt);`,
    `    `,
    `    grunt.registerTask('bootstrap4:test', 'Test Grunt', async () => {`,
    `        grunt.log.writeln(__dirname)`,
    `        grunt.log.writeln(\`BASEPATH : \${INIT_CWD}\`)`,
    `        grunt.log.writeln(\`PROCESS_BASEPATH : \${PROCESS_BASEPATH}\`)`,
    `        grunt.log.writeln(\`PROCESS_BASEPATH : \${Bootstrap4.basepath}\`)`,
    `    })`,
    `};`,
]

module.exports.Templates = {
    grunt: data.join('\n')
}
